### ISSUE TITLE
Debug mode?

### ISSUE THREAD

**Issue by JackYoungblood** [nojhan/liquidprompt#610]
Shell: bash
Operating system: Lubuntu 18.04 
Liquid Prompt version (1.11, 488bb5975db9fa8be0b795019f0b6d99ec792f50): 

Liquid Prompt is a great utility and I'm enjoying playing with it. There are so many flags that can be set that I'm having a hard  time determining which flags contributed to the final console prompt I see. It would be great if the tool had some kind of debug mode to explain which flags contributed to the final console prompt that I see. 

Right now my prompt says:
10:54:27 θ127° [:~/install] $ 

I can't figure out what the θ127° represents and which flags caused those values to be added to the output. I don't see the theta symbol, θ, in the README file.

**Comment by Rycieos** [comment]
The `θ` symbol is the default symbol for temperature:
https://github.com/nojhan/liquidprompt/blob/af63c4cfb8afe3f3161f3ace4aba3b940847a7a8/liquidprompt#L346

I really hope there is a bug in your system, because a temp of 127° seems a bit high. Try running either `sensors -u` or `acpi -t` to see what Liquidprompt is looking at to see your temps. If one of those is correctly reporting that temp, then there isn't a bug in Liquidprompt.

The request for a debug mode is a good one, and something we should look into. I'll keep this open for that.

In the meantime, if you want to see a crazy amount of debug info, you can run `set -x`, and you will see everything Liquidprompt is doing to build your PS1. Run `set +x` to disable.

**Comment by JackYoungblood** [comment]
Thank you for the response. Note that my machine does not feel particularly warm. The laptop is an HP model. A web search showed a few other ppl with a problem of a high reported temp on  acpitz-virtual-0 temp6. Should this be a cause for concern?

Here's the output from my `sensors -u`:
```
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:
  temp1_input: 68.000
  temp1_max: 87.000
  temp1_crit: 105.000
  temp1_crit_alarm: 0.000
Core 0:
  temp2_input: 68.000
  temp2_max: 87.000
  temp2_crit: 105.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 60.000
  temp3_max: 87.000
  temp3_crit: 105.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 58.000
  temp4_max: 87.000
  temp4_crit: 105.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 60.000
  temp5_max: 87.000
  temp5_crit: 105.000
  temp5_crit_alarm: 0.000

acpitz-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 59.000
  temp1_crit: 128.000
temp2:
  temp2_input: 54.000
  temp2_crit: 128.000
temp3:
  temp3_input: 47.000
  temp3_crit: 128.000
temp4:
  temp4_input: 47.000
  temp4_crit: 128.000
temp5:
  temp5_input: 32.000
  temp5_crit: 128.000
temp6:
  temp6_input: 127.000
  temp6_crit: 128.000

radeon-pci-0100
Adapter: PCI adapter
temp1:
  temp1_input: 54.000
  temp1_crit: 120.000
  temp1_crit_hyst: 90.000

```
